### ISSUE TITLE
GOG achievement support? 

### ISSUE THREAD

**Issue by Bitwolfies** [lutris/agora#109]
Would be great if we could view and unlock achievements for galaxy games.

**Comment by soredake** [comment]
This is possible if you install games from gog galaxy client.

**Comment by strycore** [comment]
We can't add support for GOG achievements, sorry

**Comment by agharbeia** [comment]
@strycore, do you mind giving us a little bit of explanation?
Is it not technically possible? Or you have no interest in the idea?

**Comment by strycore** [comment]
Actually, it might be possible to achieve now thanks to Comet: https://github.com/imLinguin/comet/

**Comment by agharbeia** [comment]
Shall we reopen this ticket, then, for completion's sake, and on the hope that someone will contribute a patch to it soon?

**Comment by strycore** [comment]
> Shall we reopen this ticket

I don't really look at this "agora" repository anymore. Comet integration will happen sometime regardless of an existing ticket.
