### ISSUE TITLE
Change Vertical Cover Image Manually?

### ISSUE THREAD

**Issue by kothavade** [lutris/agora#113]
When right clicking a game and selecting "Configure" in the Games tab, you can change or delete the horizontal cover and the icon, but not the vertical cover that is seen when increasing the zoom level. 

Can adding a third configurable image be considered, ~~and until that releases, if it does, is there a way to manually change these images~~?

#108 is related, but that seems to be about the ability to set the images in vertical mode at all, not change the image that is displayed.

Thanks.

**Comment by kothavade** [comment]
I found how to manually change them: https://github.com/lutris/lutris/issues/4265#issuecomment-1146921079, but a GUI would still be preferred.

**Comment by danieljohnson2** [comment]
We've got a GUI for this in the 0.5.12 beta, so I think this is done.

**Comment by kothavade** [comment]
> We've got a GUI for this in the 0.5.12 beta, so I think this is done.

Great to hear, thanks!
