### ISSUE TITLE
scummvm can't find libsndio.so.6.1

### ISSUE THREAD

**Issue by soredake** [lutris/agora#84]
```
❯ lutris -d 
2020-12-31 15:40:56,762: Initializing lutris
2020-12-31 15:41:03,657: Runtime up-to-date. Initialization complete.
INFO     2020-12-31 15:41:03,663 [application.do_command_line:314]:Lutris 0.5.8.1
INFO     2020-12-31 15:41:03,664 [startup.check_driver:57]:Running AMD Mesa driver 20.3.1 on Radeon RX 560 Series (POLARIS11, DRM 3.39.0, 5.9.16-xanmod1, LLVM 11.0.0) (0x67ff)
INFO     2020-12-31 15:41:03,664 [startup.check_driver:69]:GPU: 1002:67FF 1043:04BC (amdgpu drivers)
DEBUG    2020-12-31 15:41:07,405 [command.start:131]:LD_LIBRARY_PATH=";$LD_LIBRARY_PATH"
DEBUG    2020-12-31 15:41:07,405 [command.start:131]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/home/danet/.local/lib/python3.8/site-packages:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2020-12-31 15:41:07,405 [command.start:132]:/usr/share/lutris/bin/lutris-wrapper /home/danet/.local/share/lutris/runners/scummvm/bin/scummvm 0 0 /home/danet/.local/share/lutris/runners/scummvm/bin/scummvm --extrapath=/home/danet/.local/share/lutris/runners/scummvm/share/scummvm --themepath=/home/danet/.local/share/lutris/runners/scummvm/share/scummvm
Running /home/danet/.local/share/lutris/runners/scummvm/bin/scummvm --extrapath=/home/danet/.local/share/lutris/runners/scummvm/share/scummvm --themepath=/home/danet/.local/share/lutris/runners/scummvm/share/scummvm
Initial process has started with pid 52007
Start monitoring process.
/home/danet/.local/share/lutris/runners/scummvm/bin/scummvm: error while loading shared libraries: libsndio.so.6.1: cannot open shared object file: No such file or directory
Monitored process exited.
Initial process has exited (return code: 32512)
All children have exited.
Exit with returncode 32512
DEBUG    2020-12-31 15:41:07,573 [command.on_stop:180]:Process hasn't terminated yet
DEBUG    2020-12-31 15:41:07,573 [command.on_stop:182]:Process 52005 has terminated with code 0

```
https://github.com/lutris/buildbot/issues/130

**Comment by appoloin** [comment]
I'm seeing this as well, just done a clean install of 20.04 and I'm getting dependency issues from Dosbox, Scummvm. Wine works fine.    I ended up installing Scummvm and Dosbox-staging from main sites.

**Comment by soredake** [comment]
@strycore

**Comment by soredake** [comment]
After reinstalling kubuntu it can't find `libSDL2_net-2.0.so.0`

**Comment by jibsaram** [comment]
I'm getting the same issue with Lutris 0.5.8.3 on Arch (EndeavourOS). I have no issue launching ScummVM v2.2.0 installed [via the community repo](https://archlinux.org/packages/community/x86_64/scummvm/).

The version seems to have changed, as in my case it fails to find `libsndio.so.7.0`. My system comes with `libsndio.so.7.1` pre-installed. 

Comparing Lutris' ScummVM runner version with the one I installed with `scummvm --version` seems to show the latter does not list `sndio` in the  `Features compiled in` list. This can be verified with `ldd`, as it indeed does not look for `libsndio.so*`.

Creating a symlink that points to `libsndio.so.7.1` seems to allow Lutris' ScummVM to boot up successfully, though that's not the most elegant way to deal with this of course. Placing said symlink in Lutris' `~/.local/share/lutris/runtime/Ubuntu-18.04-x86_64` keeps your actual `/usr/lib` folder clean, at least until a more correct fix is found.

**Comment by kekonn** [comment]
This problem still persists, but now with libsndio.so.7.0
