### ISSUE TITLE
Use native file chooser

### ISSUE THREAD

**Issue by ObserverOfTime** [lutris/agora#87]
This is related to lutris/lutris#336 but the implementation should be much simpler.

GTK>=3.20 can use the native file chooser via [Gtk.FileChooserNative](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/FileChooserNative.html).
For example, on Linux with KDE and `GTK_USE_PORTAL=1` this will use KDialog.

You can check the version and fall back to `Gtk.FileChooserDialog` on GTK<3.20.

**Comment by soredake** [comment]
Can i ask why is this closed? Lutris from flathub-beta is still using gtk file picker by default.

**Comment by ObserverOfTime** [comment]
I was going through my issues and noticed this was implemented in lutris/lutris@907f63704a164807afd7cbf7fa88e0ac0d7b0033.

> Lutris from flathub-beta is still using gtk file picker by default.

It should use the native file chooser with `GTK_USE_PORTAL=1`.

**Comment by soredake** [comment]
> I was going through my issues and noticed this was implemented in [lutris/lutris@907f637](https://github.com/lutris/lutris/commit/907f63704a164807afd7cbf7fa88e0ac0d7b0033).

But for some reason, it does not work for me with rpm and flathub version. Does it work for you?

>It should use the native file chooser with GTK_USE_PORTAL=1.

Even with this env, it's still gtk picker.

**Comment by ObserverOfTime** [comment]
It works on Arch. Maybe your packages are outdated?

**Comment by soredake** [comment]
> It works on Arch. Maybe your packages are outdated?

I've tested in opensuse with latest kde software.

**Comment by ObserverOfTime** [comment]
You might also need to install `xdg-desktop-portal` and/or `xdg-desktop-portal-kde`.

**Comment by soredake** [comment]
> You might also need to install `xdg-desktop-portal` and/or `xdg-desktop-portal-kde`.

I have them installed, the -gtk one is installed too.
